name: Build Teensy LC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "Teensy LC"
      test-dir: "tests/teensylc"
      env-name: "teensylc"
      firmware-ext: "hex"
